#!/usr/bin/env node
/**
 * generate-context — write a minimal AI_CONTEXT.md without Python.
 */
import fs from "node:fs";
import path from "node:path";
import { REPO_ROOT, ensureDir, readTemplateVersion } from "../lib/feedback.mjs";

ensureDir("6_ai_runtime_context");
const out = path.join(REPO_ROOT, "6_ai_runtime_context/AI_CONTEXT.md");
const now = new Date().toISOString().replace("T", " ").slice(0, 19);
const body = `# AI Execution Context - Auto-Generated
**Generated:** ${now}
**Adapter:** node
**Template version:** ${readTemplateVersion()}
**Authority:** \`0_phase0_bootstrap/AI_SANDBOX_RULES.md\`
**Purpose:** Consolidated constraint context for AI chat sessions

---
## Governance
**Source:** \`1_global_standards/AI_OPERATING_CONSTITUTION.md\`

See constitution for non-negotiable rules. This file was generated by the
Node reference adapter (\`adapters/node/scripts/generate-context.mjs\`).

---
## Stack Adapter
- Active adapter: **node**
- Entry: \`meta.ps1\` / \`meta.sh\`
- Protocol: \`5_reference_architectures/STACK_ADAPTER_PROTOCOL.md\`

---
**Last Generated:** ${now}
**Generator:** \`adapters/node/scripts/generate-context.mjs\`
`;

fs.writeFileSync(out, body, "utf8");
console.log("[node:generate-context] OK — wrote 6_ai_runtime_context/AI_CONTEXT.md");
process.exit(0);
